name: Continuous Integration 
run-name: Pipeline launched by ${{ github.actor }}

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checking repository 
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Installing Dependencies
        run: npm install

      - name: Display Start Time
        run: echo "Pipeline start time :$(date)"  